baseURL = "https://wiki.nickbelzer.me/"
languageCode = "en-us"
title = "My External Brain"
theme = "docs"
footnoteReturnLinkContents = "↩"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNumbersInTable = false
    noClasses = true
    style = "github"
    tabWidth = 4
